<<<<<<< HEAD:.github/workflows/dashing_ci.yml
name: Dashing CI
=======
name: Rolling CI
>>>>>>> restructure:.github/workflows/ros_ci.yml

on:
  pull_request:
    branches:
<<<<<<< HEAD:.github/workflows/dashing_ci.yml
      - 'dashing'
      - 'dashing-devel'
=======
      - 'devel'
      - 'main'
>>>>>>> restructure:.github/workflows/ros_ci.yml

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
<<<<<<< HEAD:.github/workflows/dashing_ci.yml
          - dashing
        include:
          # Dashing Diademata (May 2019 - May 2021)
          - docker_image: ubuntu:bionic
            ros_distribution: dashing
=======
          - rolling
        include:
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: ubuntu:focal
            ros_distribution: rolling
>>>>>>> restructure:.github/workflows/ros_ci.yml
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: grbl_ros
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
