name: Generate Documentation

on:
  push:
    branches:
      - main
jobs:
  generate_docs:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup ROS environment
      uses: flynneva/setup-ros@enable_ros2_testing
      with:
        use-ros2-testing: true
        required-ros-distributions: rolling
    - name: build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && pip3 install -r requirements.txt && pip3 install sphinxcontrib-napoleon"
        build-command: '"source /opt/ros/rolling/setup.bash" && make html'
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/
