name: Generate Documentation

on:
  push:
    branches:
      - main
jobs:
  generate_docs:
    runs-on: [ubuntu-latest]
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    steps:
    - name: setup directories
      run: mkdir -p ros_ws/src/grbl_ros
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ros_ws/src/grbl_ros
    - name: build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "ros_ws/src/grbl_ros/docs/"
        pre-build-command: "apt-get update -y && pip3 install -r ros_ws/src/grbl_ros/requirements.txt && pip3 install sphinxcontrib-napoleon"
        build-command: '"make html"'
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ros_ws/src/docs/_build/html/
