name: Generate Documentation

on:
  push:
    branches:
      - main
jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install sphinx dependencies
      run: "pip3 install sphinxcontrib-napoleon"
    - name: build documentation
      run: "cd docs/ && make html && cd .."
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/
